# Generated by Django 3.2.3 on 2025-06-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgraph', '0002_category_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='timestamp',
            field=models.IntegerField(default=100),
        ),
    ]
