# Generated by Django 5.2.1 on 2025-06-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgraph', '0003_category_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nei_node_weightings',
            field=models.JSONField(default=dict),
        ),
    ]
