# Generated by Django 5.2.1 on 2025-06-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgraph', '0004_category_nei_node_weightings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='nei_node_weightings',
        ),
        migrations.AddField(
            model_name='category',
            name='neighbour_node',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='neighbour_node_weight',
            field=models.FloatField(default=0),
        ),
    ]
